language: python

python:
 - 3.6
 - 3.5
 - 3.7

before_install:
 - wget https://www4.stat.ncsu.edu/~boos/var.select/diabetes.rwrite1.txt
 - mv diabetes.rwrite1.txt diabetes.data

script:
 - python3 HW_7.py --help
 - python3 HW_7.py diabetes.data ' ' -H --interpolation "y, age, 26"
 - python3 HW_7.py diabetes.data ' ' -H --summary "y"
